### ISSUE TITLE
Problem sa linkovima

### ISSUE THREAD

**Issue by ghost** [init-conference/2019#1]
Potrebno promjeniti href-ove iz apsolutnih u relativne.

e.g. 
```html
<a class="menu__item__link scrollTo" href="https://initconf.org/#venue">Venue</a>
```
u
```html
<a class="menu__item__link scrollTo" href="/#venue">Venue</a>
```
ili prilagoditi se subdomainu
```html
<a class="menu__item__link scrollTo" href="https://2019.initconf.org/#venue">Venue</a>
```

**Severity**: nikakav, al' OCD kicks in :joy:
**Time to implement**: u zavisnosti od lijenosti devova

**Comment by miroslavpopovic** [comment]
Lijeni developeri su uskočili i riješili problem. Hvala za info Dejane ❤️.
